security:
    password_hashers:
        App\Entity\Utilisateur: 'auto'  # Vous pouvez utiliser bcrypt ou argon2i pour le hashage du mot de passe
    providers:
        users_in_database:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        main:
            # Authentification via formulaire
            form_login:
                login_path: login
                check_path: login
                default_target_path: home  # Ou la page vers laquelle vous souhaitez rediriger après la connexion
            logout:
                path: /logout  # Définissez ici le chemin de la route de déconnexion
                target: login  # Redirection après déconnexion, peut être une autre page