controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
home:
    path: /
    controller: App\Controller\HomeController::index
chat_index:
    path: /chat
    controller: App\Controller\ChatController::index

chat_send:
    path: /chat/send
    controller: App\Controller\ChatController::send
    methods: POST

utilisateur_index:
    path: /utilisateur
    controller: App\Controller\UtilisateurControleur::index

utilisateur_new:
    path: /utilisateur/new
    controller: App\Controller\UtilisateurControleur::new

utilisateur_show:
    path: /utilisateur/{id}
    controller: App\Controller\UtilisateurControleur::show

utilisateur_edit:
    path: /utilisateur/{id}/edit
    controller: App\Controller\UtilisateurControleur::edit

utilisateur_delete:
    path: /utilisateur/{id}
    controller: App\Controller\UtilisateurControleur::delete
    methods: DELETE

